// Generated by CoffeeScript 1.10.0
(function() {
  var kw;

  kw = require("./atoms").kw;

  module.exports = function(obj, path) {
    var i, len, part, value;
    path = path.trim().replace(/[ ]{2,}/g, ' ').split(' ');
    value = obj;
    for (i = 0, len = path.length; i < len; i++) {
      part = path[i];
      if (part[0] === ":") {
        part = kw(part);
      }
      if (value.exists) {
        if (value.exists(part) != null) {
          value = value.at(part);
        } else {
          throw "Could not find " + part;
        }
      } else {
        throw "Not a composite object";
      }
    }
    return value;
  };

}).call(this);
